### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by arskyy** [LoliKillers/Arnz-Api#2]
![Screenshot_20211118_064235](https://user-images.githubusercontent.com/80798056/142294577-dbce1e78-dd79-4eed-898e-852e3b655e04.jpg)
Error kak mohon di fix in

**Comment by LoliKillers** [comment]
Silahkan switch branch ke update1 dan masukkan sendiri, login/register

Saya belum ada niatan update, karna banyak yang ngejual script ini :)

**Comment by LoliKillers** [comment]
Switch branch ke update 1,  masukin aja noh sendiri

Belum ada niatan update!

**Comment by arskyy** [comment]
Update 1 apaan jir
